# Generated by Django 6.0.3 on 2026-04-21 08:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0014_add_repayment_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='land_documents',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='land_documents'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nid_card_back',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload NID card back side', max_length=255, null=True, verbose_name='nid_card_back'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nid_card_front',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload NID card front side', max_length=255, null=True, verbose_name='nid_card_front'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_picture'),
        ),
    ]
