# Generated by Django 6.0.3 on 2026-05-02 12:58

import django.db.models.deletion
import loan_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0016_seed_loan_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='land_documents',
            field=loan_app.models.CloudinaryField(blank=True, null=True, upload_to='', verbose_name='land_documents'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='nid_card_back',
            field=loan_app.models.CloudinaryField(blank=True, help_text='Upload NID card back side', null=True, upload_to='', verbose_name='nid_card_back'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nid_card_front',
            field=loan_app.models.CloudinaryField(blank=True, help_text='Upload NID card front side', null=True, upload_to='', verbose_name='nid_card_front'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=loan_app.models.CloudinaryField(blank=True, null=True, upload_to='', verbose_name='profile_picture'),
        ),
    ]
