# Generated by Django 6.0.3 on 2026-05-02 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0017_alter_farmerprofile_land_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='risk_score',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='priority_score',
            field=models.IntegerField(default=0, help_text='Auto-calculated priority score (0-100)'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
